### ISSUE TITLE
Use disable plugin definition for dependencies

### ISSUE THREAD

**Issue by acrylian** [FilippoBoscarino/smartImageCache-for-Zenphoto#2] opened 2023-03-20 16:16 UTC
![Bildschirmfoto 2023-03-20 um 17 10 25](https://user-images.githubusercontent.com/2474309/226401966-e5630774-e929-4f10-a972-abce1f9a4d6b.jpg)

Instead of this better use in the plugin main config:

      $plugin_disable = (!extensionEnabled('cacheManager')) ? gettext('cacheManager plugin is required') : false;;

This disables activation of the plugin.

Reference:
https://github.com/zenphoto/demo-plugin/blob/master/zenphoto_demoplugin.php

**Comment by FilippoBoscarino** [comment] 2023-03-20 16:28
Ok, will be fixed in an imminent 1.0.1 release

**Comment by FilippoBoscarino** [comment] 2023-03-20 18:32
Playing with cacheManager activation/deactivation in my environment (to test my plugin),  I noticed an Error 500 every time that I apply ON and OFF for your the Extension. Is there someting you can reproduce or is something wrong in my server?
It seems that extension is activated/deactivated but I got error on the next page.
Going back and reloading again plugin tab=all, fixes the issue.
It happens also with my plugin deleted at all

**Comment by acrylian** [comment] 2023-03-20 18:42
With your current plugin version active and its cacheManager check I cannot disable it as the note breaks everything. Actually once I did disable the cacheManager it stays block of course until I remove your plugin.

But a 500 error I never saw even without your plugin.

**Comment by FilippoBoscarino** [comment] 2023-03-20 19:03
Ok fixed.
It was a problem of another third part plugin I was testing that generate a Fatal Error.
Control changed

**Closed as completed** 2023-03-20 19:07 UTC
Labels: enhancement, fixed

**Comment by acrylian** [comment] 2023-03-20 19:08
Ah, good. Take a look at the releases function of the repo instead of putting the plugin in a version number folder.

**Comment by FilippoBoscarino** [comment] 2023-03-22 13:57
Sorry for bothering you, but... I really have a problem to undertand GitHub logic about releases!
I have read a lot but I do not undestand anyway.

In my space I created a brand new Repository "Zenphoto", inside a branch "smartImageCache" and two releases called "v.1.0.0" and "v.1.0.0a".
Everything is fine until here.

Problems raise up when I want to add files to releases: it permits only to upload one level list of files, no folders in the release editor.
So the only way to add the entire plugin is only adding a .zip file.
Anyway it is not included in the automatic .zip and .tar.gz it creates for the release.

I am quite sure that this is not the right solution.
Are you so kind to spend a couple of minutes to help me?

**Comment by acrylian** [comment] 2023-03-22 14:54
Not sure what you mean.  You generally only need one branch that normally is named "main". You can use separate branches for separate release streams for example a parallele 1.x and 2.x (we don#t do that btw) which both behave separately.

You don't need folders for releases. The whole repo is a release as soon as you create one. A release is created on the release tab by creating a tag for the release. That "freezes" the state of the repo at that time you did the release so to speak.

> it permits only to upload one level list of files, no folders in the release editor.

You need to create a local repository on your computer by checking out the repo. Github provides a tool called GitHub Desktop  to do that (I use a different tool called SourceTree). You then commit the changes from your local repo to the actual repo.

**Comment by acrylian** [comment] 2023-03-22 14:57
GitHub or Git is not the most intuitive tool to use (and most incl. me don't use all features) and needs some time to get used to.

**Comment by acrylian** [comment] 2023-03-22 14:58
Here's the link to GitHub's own tool: https://desktop.github.com/

**Comment by acrylian** [comment] 2023-03-22 15:00
We are using this one: https://www.sourcetreeapp.com/ (I use an older 3.x version as my Mac is a bit older currently and does not support the 4.x one).

**Comment by FilippoBoscarino** [comment] 2023-03-22 15:16
I have tried Git hub desktop bit without understanding the Logic ot the repository It seems a worst mess...I assume It Is possible to achieve the goal by web, and try do manager by that, and only later introduce complexity of a client.So if i correctly understand i can create a repository and fullfill It with wanted set of files to have a release of a project.Than uploading a new set (overwriting) It understands It Is a new version.Something like that?Il 22 mar 2023 16:00, Malte Müller ***@***.***> ha scritto:
We are using this one: https://www.sourcetreeapp.com/ (I use an older 3.x version as my Mac is a bit older currently and does not support the 4.x one).

**Comment by acrylian** [comment] 2023-03-22 15:23
> So if i correctly understand i can create a repository and fullfill It with wanted set of files to have a release of a project.Than uploading a new set (overwriting) It understands It Is a new version.Something like that?

Yes, basically. With such a client like desktop it notices these changes itself. It is like using a folder for say Google Drive or Dropbox locally (in case you know these). Doing all this via the website is really overcomplicated and I don't think you actually can do the same as you noticed you cannot upload several files or a folder (btw you cannot commit an empty folder in any case).

It is really better to use a local folder where you do your changes and then commit these to the repo. 

I perhaps would recommend to create a test repo and just experiment with some simple (text) files to get a bit used to it.

**Comment by FilippoBoscarino** [comment] 2023-03-22 15:25
Ok, many thanks. I will experiment a bit with your tool because the Git ones seems not so friendly

**Comment by FilippoBoscarino** [comment] 2023-03-22 19:32
I definitively admit that GitHub logic is far miles from my habits...
I think I succeeded in upload it with releases
You should find the corrected last release v.1.0.0a with all known bugs fixed at
[smartImageCache](https://github.com/FilippoBoscarino/smartImageCache)

Please let me know both if you find the release correctly and if it works in your environment

**Comment by acrylian** [comment] 2023-03-22 19:42
I will try to test tomorrow. But your version numbers are off now ;-) 1.0.0a is actually an alpha pre-release version  (as would be 1.0.0b as beta) that comes before 1.0.0. Your next version would be 1.0.1 and then first if you release pre-versions  (we don't currently, we just name them internally) 1.0.1a until fully ready. We generally (try to) follow semantic versioning as laid out here https://semver.org/ (you don't need to but it is a good guide).

**Comment by FilippoBoscarino** [comment] 2023-03-23 08:22
;)
I find out a new bug, already fixed: two lines of code swapped that generate a fatal error.
I will reproduce a new version soon and I'll fix te versioning too.

**Comment by FilippoBoscarino** [comment] 2023-03-23 08:51
Just an info to share.
I noticed that in my environment, corrupted cache sizes are pratically reduced to zero with this plugin (only some sizes on panoramic pics jpeg sources stills, but thay can be really huge in size 10mb or more).
I use Imagick with cURL setup, and swapping to GDlibrary for a while, reproducing missed sizes and reswap again, fixes the issue.
But I noticed that rather a significant number of sizes, caming from the background process of the edit page (don't worry, significant means not more dan 1%) are finded already cached but corrupted by my plugin.
I mean the file is present but unreadable and it is showed as broken image in the results page.
Strangely the issues appears to be related only to 80x80 sizes, never happened to 40x40.
Larger is number of images in the Album, larger is the possibility that happens.

I think that the problem is that the background option could be sometimes a critical operation, because it attempts to create many sizes all togheter.
I haven't had time to analyze the generating function itself yet, but I think this info could be useful for you to understand if there is any pitfall in the process

**Comment by acrylian** [comment] 2023-03-23 09:05
Thanks. Yes, if you are calling a page with several or lots of images the script will try to create what is missing. There is a limit via the zpmutex class to not overload the server with requests. But certainly depending on the server it may fail on some images just as the cacheManager in primarily classic mode does.

**Comment by FilippoBoscarino** [comment] 2023-03-23 09:07
The unconfortable situation is that they appear as done, so not automatically regenerated, but corrupted

**Comment by acrylian** [comment] 2023-03-23 09:10
Okay, I see. Are those 0 byte files?

**Comment by FilippoBoscarino** [comment] 2023-03-23 09:14
Sometimes 0 bytes files, sometimes, if seen on browser, a little white square like 10x10 pixel.
Of course we are talking of images for backend so It Is not a "Blue" error...

**Comment by FilippoBoscarino** [comment] 2023-03-23 12:28
Finally I won against the dragon GitHub :)
Now you can find the final repository with correct versioning at
https://github.com/FilippoBoscarino/smartImageCache-for-Zenphoto
A version v.1.0.2 of the plugin is uploaded, and should be finally reliable by my point of view.

Soon I will remove the other Repositories, **this included**.
So please for every new notice use the one above.
Cheers!

**Comment by acrylian** [comment] 2023-03-23 12:32
Okay, not sure why you created a new one but whatever works ;-)

**Comment by FilippoBoscarino** [comment] 2023-03-23 12:34
> why you created a new one

Experimenting with Git and Sourcetree clients have produced some strange things I was not able to roll back anymore.

I am transferring this thread to the new repository, just for tracking purposes.
